#!/bin/bash

# entry into container

function clean_up {

    # Perform program exit housekeeping
    echo "shutdown signal handled"

    # stop lwsm
    if [ `pidof lwsmd` ];  then
        /opt/likewise/bin/lwsm shutdown
        while [ `pidof lwsmd` ];  do
            sleep 1
        done

    fi
    exit $1
}

trap clean_up SIGHUP SIGINT SIGTERM

/opt/likewise/sbin/lwsmd &
sleep 1

echo "perform autostart"
/opt/likewise/bin/lwsm autostart

if [ $? -ne 0 ]; then
    echo "failed to autostart services"
    clean_up 1
fi

sleep 1

CONFIG_FILE=/var/lib/vmware/config/lightwave-client.cfg

if [ -f $CONFIG_FILE ]; then
    DOMAIN=$(grep "^domain=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    ADMIN=$(grep "^admin=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    PASSWORD=$(grep "^password=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    SITE=$(grep "^site-name=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    POST_PARTNER=$(grep "^post-partner-hostname=" $CONFIG_FILE | awk -F"=" '{print$2;}')

    if [ -z "$SITE" ]; then
        exec 3<<<$PASSWORD
        /opt/vmware/bin/ic-join --domain $DOMAIN \
                                --username $ADMIN \
                                <&3
    else
        exec 3<<<$PASSWORD
        /opt/vmware/bin/ic-join --domain $DOMAIN \
                                --username $ADMIN \
                                --site $SITE \
                                <&3
    fi

    if [ -z "$POST_PARTNER" ]; then
        exec 3<<<$PASSWORD
        /opt/vmware/bin/post-cli node promote \
            --host-name `hostname -f` \
            --domain-name $DOMAIN \
            <&3
    else
        exec 3<<<$PASSWORD
        /opt/vmware/bin/post-cli node promote \
            --host-name `hostname -f` \
            --partner-name $POST_PARTNER \
            <&3
    fi
fi

while :
do
    sleep 5 &
    wait
done
