#! /bin/sh
### BEGIN INIT INFO
# Provides: vmdir
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start and Stop vmdir
### END INIT INFO

PREFIX="/opt/likewise"
SERVICE_NAME="vmdir"

export KRB5_CONFIG=/etc/krb5.lotus.conf

. /opt/likewise/bin/init-lwsm.sh
