#!/bin/bash -x

LW_CONFIG_PATH=/var/lib/vmware/config/lightwave-server.cfg

function clean_up {

    # Perform program exit housekeeping
    echo "shutdown signal handled"

    # stop java processes
    /opt/vmware/sbin/vmware-stsd.sh stop

    # stop lwsm
    if [ `pidof lwsmd` ];  then
        /opt/likewise/bin/lwsm shutdown
        while [ `pidof lwsmd` ];  do
            sleep 1
        done

    fi
    exit $1
}

trap clean_up SIGHUP SIGINT SIGTERM

# entry into container

# Need haveged for vmca
/usr/sbin/haveged -w 1024 -v 1

/opt/vmware/bin/configure-lightwave-server --config-file $LW_CONFIG_PATH 2>&1 > /tmp/configure-lightwave-server.log

if [ $? -ne 0 ]; then
    echo "failed to configure lightwave server"
    clean_up 1
fi

/opt/likewise/sbin/lwsmd &
sleep 1

echo "perform autostart"
/opt/likewise/bin/lwsm autostart

if [ $? -ne 0 ]; then
    echo "failed to autostart services"
    clean_up 1
fi

sleep 1

/opt/vmware/sbin/vmware-stsd.sh start

if [ $? -ne 0 ]; then
    echo "failed to start secure token service"
    clean_up 1
fi

while :
do
    sleep 5 &
    wait
done
