# Map any Linux path separators "/" to Windows path separators "\"
#

JDK_BASE = $(LIGHTWAVE_JDK_ROOT:/=\)

JAVAH = $(JDK_BASE)\bin\javah.exe
CLASSNAME = com.vmware.identity.cdc.CdcAdapter
JARDIR=..\..\..\build\authentication-framework\packages\client-domain-controller-cache.jar


all: cdcjni.h

cdcjni.h: $(JARDIR)
    @echo $(JAVAH) -o ..\cdcjni.h -classpath $(JARDIR) $(CLASSNAME)
    $(JAVAH) -o ..\cdcjni.h -classpath $(JARDIR) $(CLASSNAME)

clean:
    -del /f ..\cdcjni.h
