MKDIR=/bin/mkdir
RM=/bin/rm
RMDIR=/bin/rm -rf
CP=/bin/cp
MV=/bin/mv
TAR=/bin/tar
RPM=/bin/rpm
SED=/usr/bin/sed

SRCROOT := $(realpath $(SRCROOT))

LIGHTWAVE_STAGE_DIR=$(SRCROOT)/stage

ARCH=x86_64

VMDIR_SRCROOT=$(SRCROOT)/vmdir
VMDIR_PKGDIR=$(VMDIR_SRCROOT)/build/rpmbuild/RPMS/$(ARCH)

VMDIR_MAJOR_VER=6
VMDIR_MINOR_VER=0
VMDIR_RELEASE_VER=0
VMDIR_PATCH_VER=0
VMDIR_VERSION=$(VMDIR_MAJOR_VER).$(VMDIR_MINOR_VER).$(VMDIR_RELEASE_VER)-$(VMDIR_PATCH_VER)
VMDIR_SERVER_PKG_NAME=vmware-directory
VMDIR_CLIENT_PKG_NAME=vmware-directory-client
VMDIR_CLIENT_DEVEL_PKG_NAME=vmware-directory-client-devel
VMDIR_SERVER_RPM=$(VMDIR_SERVER_PKG_NAME)-$(VMDIR_VERSION).$(ARCH).rpm
VMDIR_CLIENT_RPM=$(VMDIR_CLIENT_PKG_NAME)-$(VMDIR_VERSION).$(ARCH).rpm
VMDIR_CLIENT_DEVEL_RPM=$(VMDIR_CLIENT_DEVEL_PKG_NAME)-$(VMDIR_VERSION).$(ARCH).rpm
VMDIR_RPMS=$(VMDIR_SERVER_RPM) $(VMDIR_CLIENT_RPM) $(VMDIR_CLIENT_DEVEL_RPM)

VMAFD_SRCROOT=$(SRCROOT)/vmafd
VMAFD_PKGDIR=$(VMAFD_SRCROOT)/build/rpmbuild/RPMS/$(ARCH)

VMAFD_MAJOR_VER=6
VMAFD_MINOR_VER=0
VMAFD_RELEASE_VER=0
VMAFD_PATCH_VER=0
VMAFD_VERSION=$(VMAFD_MAJOR_VER).$(VMAFD_MINOR_VER).$(VMAFD_RELEASE_VER)-$(VMAFD_PATCH_VER)
VMAFD_SERVER_PKG_NAME=vmware-afd
VMAFD_CLIENT_PKG_NAME=vmware-afd-client
VMAFD_CLIENT_DEVEL_PKG_NAME=vmware-afd-client-devel
VMAFD_SERVER_RPM=$(VMAFD_SERVER_PKG_NAME)-$(VMAFD_VERSION).$(ARCH).rpm
VMAFD_CLIENT_RPM=$(VMAFD_CLIENT_PKG_NAME)-$(VMAFD_VERSION).$(ARCH).rpm
VMAFD_CLIENT_DEVEL_RPM=$(VMAFD_CLIENT_DEVEL_PKG_NAME)-$(VMAFD_VERSION).$(ARCH).rpm
VMAFD_RPMS=$(VMAFD_SERVER_RPM) $(VMAFD_CLIENT_RPM) $(VMAFD_CLIENT_DEVEL_RPM)

VMCA_SRCROOT=$(SRCROOT)/vmca
VMCA_PKGDIR=$(VMCA_SRCROOT)/build/rpmbuild/RPMS/$(ARCH)

VMCA_MAJOR_VER=6
VMCA_MINOR_VER=0
VMCA_RELEASE_VER=0
VMCA_PATCH_VER=0
VMCA_VERSION=$(VMCA_MAJOR_VER).$(VMCA_MINOR_VER).$(VMCA_RELEASE_VER)-$(VMCA_PATCH_VER)
VMCA_SERVER_PKG_NAME=vmware-ca
VMCA_CLIENT_PKG_NAME=vmware-ca-client
VMCA_CLIENT_DEVEL_PKG_NAME=vmware-ca-client-devel
VMCA_SERVER_RPM=$(VMCA_SERVER_PKG_NAME)-$(VMCA_VERSION).$(ARCH).rpm
VMCA_CLIENT_RPM=$(VMCA_CLIENT_PKG_NAME)-$(VMCA_VERSION).$(ARCH).rpm
VMCA_CLIENT_DEVEL_RPM=$(VMCA_CLIENT_DEVEL_PKG_NAME)-$(VMCA_VERSION).$(ARCH).rpm
VMCA_RPMS=$(VMCA_SERVER_RPM) $(VMCA_CLIENT_RPM) $(VMCA_CLIENT_DEVEL_RPM)

CFG_SRCROOT=$(SRCROOT)/config
CFG_PKGDIR=$(CFG_SRCROOT)/build/rpmbuild/RPMS/$(ARCH)

CFG_MAJOR_VER=1
CFG_MINOR_VER=0
CFG_RELEASE_VER=0
CFG_PATCH_VER=0
CFG_VERSION=$(CFG_MAJOR_VER).$(CFG_MINOR_VER).$(CFG_RELEASE_VER)-$(CFG_PATCH_VER)
CFG_PKG_NAME=vmware-ic-config
CFG_RPM=$(CFG_PKG_NAME)-$(CFG_VERSION).$(ARCH).rpm

