//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.10 at 12:40:22 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.rsa.com/names/2009/12/std-ext/WS-Trust1.4/advice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rsa.names._2009._12.std_ext.ws_trust1_4.advice;
