// generic error (range 1000 - 1999)
#define ERROR_INVALID_CONFIGURATION     1000
#define ERROR_DATA_CONSTRAIN_VIOLATION  1001
#define ERROR_OPERATION_INTERRUPT       1002

// object sid generation
#define ERROR_ORG_LIMIT_EXCEEDED        1003
#define ERROR_RID_LIMIT_EXCEEDED        1004
#define ERROR_ORG_ID_GEN_FAILED         1005
#define ERROR_NO_OBJECT_SID_GEN         1006

// ACL/SD
#define ERROR_NO_SECURITY_DESCRIPTOR    1007
#define ERROR_NO_OBJECTSID_ATTR         1008
#define ERROR_TOKEN_IN_USE              1009
#define ERROR_NO_MYSELF                 1010

#define ERROR_BAD_ATTRIBUTE_DATA        1011
#define ERROR_PASSWORD_TOO_LONG         1012

#define ERROR_CANNOT_PROMOTE_VMDIR      1013
#define ERROR_CANNOT_DEMOTE_VMDIR       1014
#define ERROR_CANNOT_JOIN_VMDIR         1015
#define ERROR_CANNOT_LEAVE_VMDIR        1016
#define ERROR_CANNOT_SPLIT_VMDIR        1017
#define ERROR_CANNOT_MERGE_VMDIR        1018

#define ERROR_CANNOT_PROMOTE_VMDIR_ALREADY_PROMOTED    1019
#define ERROR_CANNOT_CREATE_KERBEROS_CONFIGURATION    1020
#define ERROR_CANNOT_CONNECT_VMAFD      1021
