/*
 * Copyright (C) 2011 VMware, Inc. All rights reserved.
 *
 * Module   : vmauthsvc.idl
 *
 * Abstract :
 *
 *            VMware Authsvc Service
 *
 *            Interface Definition
 *
 *            Core API
 *
 * Authors  : Sriram Nambakam (snambakam@vmware.com)
 *
 */
[
    uuid (D92ED33E-A62E-11E2-AB62-000C29B1C8FE),
    version(1.0),
    pointer_default(unique)
]

interface vmauthsvc
{
#ifndef _WIN32
    #include <lw/types.h>
#else // _WIN32
    #define UINT32 unsigned int
    typedef unsigned char BYTE;
#endif

#include <vmauthsvctypes.h>

    UINT32
    VmAuthsvcRpcJoinRealm(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszPassword,
        [in]                 wstring_t pwszMachineName,
        [in]                 wstring_t pwszDomainName,
        [in]                 wstring_t pwszOrgUnit);

    UINT32
    VmAuthsvcRpcLeaveRealm(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszDomainName);

    UINT32
    VmAuthsvcRpcIsJoinedToVMDirectory(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszDomainName);

    UINT32
    VmAuthsvcRpcJoinADDomain(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszPassword,
        [in]                 wstring_t pwszMachineName,
        [in]                 wstring_t pwszDomainName,
        [in]                 wstring_t pwszOrgUnit);

    UINT32
    VmAuthsvcRpcLeaveADDomain(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszDomainName);

    UINT32
    VmAuthsvcRpcIsJoinedToADDomain(
        [in]                 handle_t hBinding,
        [in]                 wstring_t pwszServerName,
        [in]                 wstring_t pwszUserName,
        [in]                 wstring_t pwszDomainName);
}
