#!/bin/bash

function check_lightwave_join
{
    node=$1
    expected_domain=$2
    # Check if lightwave node is joined
    attempts=1
    joined="false"
    total_attempts=10
    sleep 5
    while [ $attempts -lt $total_attempts ] && [ $joined != "true" ]; do
       actual_domain=$(docker exec -it $node /opt/vmware/bin/vmafd-cli get-domain-name --server-name localhost)
       actual_domain=${actual_domain//[[:space:]]/}
       if [[ $actual_domain == $expected_domain ]]; then
            joined="true"
            break;
        else
            echo "Lightwave not joined (attempt $attempts/$total_attempts), will try again."
            attempts=$[$attempts+1]
            sleep 5
        fi
    done

    if [ $attempts -eq $total_attempts ]; then
       echo "Could not join $node to Lightwave Domain [$expected_domain] after $total_attempts attempts"
       exit 1
    else
       echo "Lightwave client at $node has been successfully joined to domain [$expected_domain]."
    fi
}

LIGHTWAVE_DOMAIN=lw-testdom.com
LIGHTWAVE_PASSWORD='Passw0rd$'
LIGHTWAVE_SITE=Default-first-site
LIGHTWAVE_HOSTNAME=lw-c-0.lw-testdom.com

LIGHTWAVE_HOME=$HOME/lightwave
LIGHTWAVE_CONFIG_DIR=$LIGHTWAVE_HOME/config-lw-c-0
LIGHTWAVE_CONFIG_PATH=$LIGHTWAVE_CONFIG_DIR/lightwave-client.cfg

mkdir -p $LIGHTWAVE_CONFIG_DIR

cat << EOF > $LIGHTWAVE_CONFIG_PATH
domain=$LIGHTWAVE_DOMAIN
hostname=$LIGHTWAVE_HOSTNAME
admin=Administrator
password=$LIGHTWAVE_PASSWORD
site-name=$LIGHTWAVE_SITE
EOF

docker run -d \
           --name lightwave-client-1 \
           --privileged \
           --net lightwave \
           --hostname $LIGHTWAVE_HOSTNAME \
           --ip 192.168.114.6 \
           --dns 192.168.114.3 \
           --dns 192.168.114.4 \
           --dns 192.168.114.5 \
           --dns-search lw-testdom.com \
           -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
           -v $LIGHTWAVE_CONFIG_DIR:/var/lib/vmware/config \
           vmware/lightwave-client-photon3

check_lightwave_join lightwave-client-1 $LIGHTWAVE_DOMAIN
