[uuid(0dc138c1-138f-4e1c-834c-846f3b189b19),
 version(1.0),
 pointer_default(unique)
]


interface vmdir_ms_pac
{
#include <ms_pac_type.h>

    void VmKdcNdrEncodeLogonInfo(
        [in] handle_t h,
        [in, unique] KERB_VALIDATION_INFO *pac);

    void VmKdcNdrDecodeLogonInfo(
        [in] handle_t h,
        [out] KERB_VALIDATION_INFO **pac);
}
