/*
 * Copyright (C) 2014 VMware, Inc. All rights reserved.
 *
 * Module   : defines.h
 *
 * Abstract :
 *
 */

typedef enum
{
    VECS_COMMAND_UNKNOWN = 0,
    VECS_COMMAND_STORE_CREATE,
    VECS_COMMAND_STORE_LIST,
    VECS_COMMAND_STORE_DELETE,
    VECS_COMMAND_STORE_PERMISSION,
    VECS_COMMAND_STORE_GET_PERMISSIONS,
    VECS_COMMAND_ENTRY_CREATE,
    VECS_COMMAND_ENTRY_LIST,
    VECS_COMMAND_ENTRY_GETCERT,
    VECS_COMMAND_ENTRY_GETKEY,
    VECS_COMMAND_ENTRY_DELETE
} VECS_COMMAND, *PVECS_COMMAND;

typedef enum
{
    VECS_PERMISSION_MODE_UNKNOWN = 0,
    VECS_PERMISSION_MODE_GRANT,
    VECS_PERMISSION_MODE_REVOKE
} VECS_PERMISSION_MODE, *PVECS_PERMISSION_MODE;


#define BAIL_ON_VECS_CLI_ERROR(dwError, message) \
  if (dwError) \
  { \
      fprintf (stderr, "Error: %s\n", message); \
      goto error; \
  }

