#!/bin/bash

# entry into container

function clean_up {

    # Perform program exit housekeeping
    echo "shutdown signal handled"

    # stop lwsm
    if [ `pidof lwsmd` ];  then
        /opt/likewise/bin/lwsm shutdown
        while [ `pidof lwsmd` ];  do
            sleep 1
        done

    fi

    exit $1
}

trap clean_up SIGHUP SIGINT SIGTERM

/opt/likewise/sbin/lwsmd &
sleep 1

echo "perform autostart"
/opt/likewise/bin/lwsm autostart

if [ $? -ne 0 ]; then
    echo "failed to autostart services"
    clean_up 1
fi

sleep 1

CONFIG_FILE=/var/lib/vmware/config/lightwave-client.cfg

if [ -f $CONFIG_FILE ]; then
    DOMAIN=$(grep "^domain=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    ADMIN=$(grep "^admin=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    PASSWORD=$(grep "^password=" $CONFIG_FILE | awk -F"=" '{print$2;}')
    SITE=$(grep "^site-name=" $CONFIG_FILE | awk -F"=" '{print$2;}')

    if [ -z "$SITE" ]; then
        exec 3<<<$PASSWORD
        /opt/vmware/bin/ic-join --domain $DOMAIN \
                                --username $ADMIN <&3
    else
        exec 3<<<$PASSWORD
        /opt/vmware/bin/ic-join --domain $DOMAIN \
                                --username $ADMIN \
                                --site $SITE <&3
    fi
fi

if [ $? -ne 0 ]; then
    echo "failed to join lw domain"
    clean_up 1
fi

CERT_PATH=/etc/vmware/ssl

mkdir -p $CERT_PATH

/opt/vmware/bin/vecs-cli entry getkey --store MACHINE_SSL_CERT \
                                --alias __MACHINE_CERT \
                                --output $CERT_PATH/machine-ssl.key.tmp

sed '/^\s*$/d' $CERT_PATH/machine-ssl.key.tmp > $CERT_PATH/machine-ssl.key

chmod 0400 $CERT_PATH/machine-ssl.key

rm -f $CERT_PATH/machine-ssl.key.tmp

/opt/vmware/bin/vecs-cli entry getcert --store MACHINE_SSL_CERT \
                                 --alias __MACHINE_CERT \
                                 --output $CERT_PATH/machine-ssl.crt

cert_alias=$(/opt/vmware/bin/vecs-cli entry list --store TRUSTED_ROOTS | \
                                                    grep "Alias" | \
                                                    cut -d: -f2)

for cert in $cert_alias
do
/opt/vmware/bin/vecs-cli entry getcert --store TRUSTED_ROOTS \
                                             --alias $cert \
                                             --output $CERT_PATH/cert.tmp

cat $CERT_PATH/cert.tmp >> $CERT_PATH/trusted-ssl.crt

done

rm -f $CERT_PATH/cert.tmp

echo "running stssetup install ....."
ADMINUPN="$ADMIN@$DOMAIN"

/opt/vmware/bin/stssetup install \
  -admin-pwd=$PASSWORD \
  -admin-uname=$ADMINUPN \
  -cfg-file='/etc/vmware/stssrv.conf' \
  -dir-certs-file='/etc/vmware/ssl/trusted-ssl.crt' \
  -log-file=/var/lwlogs/stslog.log \
  -log-level=4 \
  -port=443 \
  -primary \
  -sts-endpoint='lw-sts-0.lw-testdom.com:443' \
  -site=$SITE \
  -system-tenant=$DOMAIN \
  -tls-cert-file='/etc/vmware/ssl/machine-ssl.crt' \
  -tls-key-file='/etc/vmware/ssl/machine-ssl.key' \
  -enabled-heads='oidc,rest' \
  -daemon-group=lightwave \
  -daemon-user=lightwave \
  -quiet

if [ $? -ne 0 ]; then
    echo "failed to setup sts: log file=/var/lwlogs/stslog.log"
    clean_up 1
fi

su -c '/opt/vmware/sbin/stssrv -config=/etc/vmware/stssrv.conf' -s /bin/sh lightwave

