
package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "STSService", targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", wsdlLocation = "/WEB-INF/wsdl/STSService.wsdl")
public class STSService_Service
    extends Service
{

    private final static URL STSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STSSERVICE_EXCEPTION;
    private final static QName STSSERVICE_QNAME = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", "STSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("/WEB-INF/wsdl/STSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STSSERVICE_WSDL_LOCATION = url;
        STSSERVICE_EXCEPTION = e;
    }

    public STSService_Service() {
        super(__getWsdlLocation(), STSSERVICE_QNAME);
    }

    public STSService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STSSERVICE_QNAME, features);
    }

    public STSService_Service(URL wsdlLocation) {
        super(wsdlLocation, STSSERVICE_QNAME);
    }

    public STSService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STSSERVICE_QNAME, features);
    }

    public STSService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public STSService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns STSService
     */
    @WebEndpoint(name = "STSService_Port")
    public STSService getSTSServicePort() {
        return super.getPort(new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", "STSService_Port"), STSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STSService
     */
    @WebEndpoint(name = "STSService_Port")
    public STSService getSTSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", "STSService_Port"), STSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STSSERVICE_EXCEPTION!= null) {
            throw STSSERVICE_EXCEPTION;
        }
        return STSSERVICE_WSDL_LOCATION;
    }

}
