#! /bin/sh
### BEGIN INIT INFO
# Provides: vmcad
# Required-Start: $network $remote_fs vmafdd
# Required-Stop: $network $remote_fs vmafdd
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start and Stop vmca
### END INIT INFO

PREFIX="/opt/likewise"
SERVICE_NAME="vmca"

. /opt/likewise/bin/init-lwsm.sh
