//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.02 at 03:10:45 PM EET 
//

package org.oasis_open.docs.ws_sx.ws_trust._200512;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RenewingType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RenewingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Allow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="OK" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenewingType")
public class RenewingType {

    @XmlAttribute(name = "Allow")
    protected Boolean allow;
    @XmlAttribute(name = "OK")
    protected Boolean ok;

    /**
     * Gets the value of the allow property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isAllow() {
        return allow;
    }

    /**
     * Sets the value of the allow property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setAllow(Boolean value) {
        this.allow = value;
    }

    /**
     * Gets the value of the ok property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isOK() {
        return ok;
    }

    /**
     * Sets the value of the ok property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setOK(Boolean value) {
        this.ok = value;
    }

}
