#!/bin/bash

# entry into container

function clean_up {

    # Perform program exit housekeeping
    echo "shutdown signal handled"

    # stop lwsm
    if [ `pidof lwsmd` ];  then
        /opt/likewise/bin/lwsm shutdown
        while [ `pidof lwsmd` ];  do
            sleep 1
        done

    fi
    exit $1
}

trap clean_up SIGHUP SIGINT SIGTERM

/opt/likewise/sbin/lwsmd &
sleep 1

echo "perform autostart"
/opt/likewise/bin/lwsm autostart

if [ $? -ne 0 ]; then
    echo "failed to autostart services"
    clean_up 1
fi

sleep 1

while :
do
    sleep 5 &
    wait
done
